language: node_js
cache: npm

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - commitlint-travis
  - npm run ci

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
